server:
  port: 8081

spring:
  application:
    name: cat-rescue-web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat_rescue?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.miaoxing.business.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.miaoxing: info
